# Specify the system matrices and the disturbances of the lti system
# It will be used to record the input state trajectory for the hankel matrix
lti_system:
  a_system_matrix:
  - [1,1]
  - [0,1]
    
  b_input_matrix:
  - [0]
  - [1]

  x_initial_state:
  - [0]
  - [1]

  # Specify the type of disturbance for each state
  types_of_disturbances: # gaussian/uniform/triangular/lognormal
  - "lognormal"
  - "gaussian"

input_sequence: [1,-1,0,2,3,-4,0,-6,2]

number_of_measurements: 300

disturbance_estimation: "discounted_kde" # gaussian_process/traditional_kde/discounted_kde


dict:

 hallo:
 - 3
 - 4

 ballo: [5,6]

 kallo:
 - [5,6]
 - [7,8]

