# Specify the system matrices and the disturbances of the lti system
# It will be used to record the input state trajectory for the hankel matrix and to simulate the "real" system
lti_system:
  a_system_matrix:
  - [1,1,0]
  - [0,1,1]
  - [0,0,1]
    
  b_input_matrix:
  - [0,1]
  - [1,0]
  - [1,0]

  x_initial_state:
  - [0]
  - [1]
  - [2]

  # Specify the type of disturbance for each state
  types_of_disturbances: # gaussian/uniform/triangular/lognormal
  - "uniform"
  - "uniform"
  - "uniform"

input_sequence: 
- [1,-1,0,2,3,-4,0,-6,2,2,3,-4,0,-6,2,4,7,6,-3,-2,4,-3,8,-5,3,2,4,5,3]
- [-1,0,2,3,-4,0,-6,2,4,2,3,-4,0,-6,2,5,8,3,4,5,2,9,-2,-1,4,-6,-8,4,-2]

number_of_measurements: 300

disturbance_estimation: "gaussian_process" # gaussian_process/traditional_kde/discounted_kde

discounted_kde:
 base_of_exponential_weights: 1.00

 density_number_of_past_samples_considered: 200

gaussian_process:

 density_number_of_past_samples_considered: 10

mpc_cost_matrices:
  R:
  - [1,0,0]
  - [0,1,0]
  - [0,0,1]

  Q:
  - [1,0]
  - [0,1]

constraints:
  G_u:
  - [1,0]
  - [0,1]

  g_u:
  - [20]
  - [20]

  G_x:
  - [1,0,0]
  - [1,1,0]
  - [0,0,1]

  g_x:
  - [30]
  - [30]
  - [30]

prediction_horizon: 3

